// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlv_DAO0yjo_lT35Q8nMVckSQd1SLxpEw',
    appId: '1:169522156048:web:c931c71ecf7e7676bbf095',
    messagingSenderId: '169522156048',
    projectId: 'app01-de7e9',
    authDomain: 'app01-de7e9.firebaseapp.com',
    storageBucket: 'app01-de7e9.appspot.com',
    measurementId: 'G-WBCGDX9156',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYqvt5P-XjGwm3mbflu9sVdd4IVoqCTBE',
    appId: '1:169522156048:android:da706ac40b0d4761bbf095',
    messagingSenderId: '169522156048',
    projectId: 'app01-de7e9',
    storageBucket: 'app01-de7e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpF_KVafnc2e3o_uPjpXErbLQ7bRZbzRY',
    appId: '1:169522156048:ios:aaa0b195a09a2b87bbf095',
    messagingSenderId: '169522156048',
    projectId: 'app01-de7e9',
    storageBucket: 'app01-de7e9.appspot.com',
    iosBundleId: 'com.example.app01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpF_KVafnc2e3o_uPjpXErbLQ7bRZbzRY',
    appId: '1:169522156048:ios:aaa0b195a09a2b87bbf095',
    messagingSenderId: '169522156048',
    projectId: 'app01-de7e9',
    storageBucket: 'app01-de7e9.appspot.com',
    iosBundleId: 'com.example.app01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlv_DAO0yjo_lT35Q8nMVckSQd1SLxpEw',
    appId: '1:169522156048:web:e20ba473b5b1f0b2bbf095',
    messagingSenderId: '169522156048',
    projectId: 'app01-de7e9',
    authDomain: 'app01-de7e9.firebaseapp.com',
    storageBucket: 'app01-de7e9.appspot.com',
    measurementId: 'G-VDV47HL0VD',
  );
}
